version: '3.8'

services:

  hub:
    image: selenium/hub:4.2.0
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    
  chrome:
    image: selenium/node-chrome:4.2.0
    command: bash cd ~ && wget https://s3.eu-central-1.amazonaws.com/semenshpak.gosuslugi.ru/newfile.mjpeg
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_SESSION_TIMEOUT=80
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 4096000000
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker

  firefox:
    image: selenium/node-firefox:4.2.0
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_SESSION_TIMEOUT=80
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 4096000000
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker

  edge:
    image: selenium/node-edge:4.2.0
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_SESSION_TIMEOUT=80
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 4096000000
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
